### PR TITLE
Delete archub.dm

### PR DESCRIPTION
**Pull request by AffectedArc07**
Hub V2 was cancelled because it relied on people hardcoding their stuff into their codebase which was sub-optimal (and thats an understatement)

### CODE REVIEW

**Comment by ShrkByte** [comment]
lame

**Comment by AffectedArc07** [comment]
Have fun with your excess CPU being wasted

**Comment by ShrkByte** [comment]
I closed this and opened another to fix the removal, you forgot the include in tgstation.dme

**Comment by AffectedArc07** [comment]
Oh the other two places I PR'd this to merged straight away
Yikes

**Pull request closed without merging**
