### PR TITLE
Removes automatic tail wagging when receiving headpats

### PR DESCRIPTION
**Pull request by Looreydev**
[Changelogs]: 

:cl: headpats
del: removed automatic tail wagging when receiving a headpat
/:cl:

[why]: 

Multiple users suggested it on discord and considering the '*wag' emote exists this shouldn't be a thing.

(don't mind the other files, i forgot to keep my master updated)

### CODE REVIEW

**Comment by Looreydev** [comment]
Travis check is failing because it just stops right in the middle 😢

**Comment by Looreydev** [comment]
`Shutdown complete
Test run failed!
Unit Tests failed!
cat: travis_test/data/logs/travis/clean_run.lk: No such file or directory
The command "tools/travis/build_byond.sh" exited with 1.`

There you go, that's why.

**Comment by Bran34** [comment]
but why

**Comment by ShrkByte** [comment]
fixed travis. 

Fix this PR holy shit.

**Comment by Looreydev** [comment]
Time to not fix the PR and go with #123

**Pull request closed without merging**
