### PR TITLE
Kilostation

### PR DESCRIPTION
**Pull request by TheMocheeze**
## About The Pull Request
This ports Kilostation to Shadow code while making a few changes for playability and to meet our needs.

## Why It's Good For The Game
Kilostation is a dense, but deeply detailed map that raises the bar for maps compared to our current options. The more options we have, the better, and Kilo is a well-thought out station with rich lore and gameplay opportunities that surpass even our other newer maps.

## Changelog
:cl:
add: Add Kilostation and its associated shuttle .dmm map files
tweak: Added cryo pods to dorm, removed certain incompatible map objects (pending substitution if problematic. To be determined by playtests.)
/:cl:

### CODE REVIEW

**Comment by ShrkByte** [comment]
Bartender's shotgun ammo is currently buckshot instead of beanbags. This needs to be changed.

**Comment by TheMocheeze** [comment]
Bottom left engineering emitter cant be safely turned on. Plasma tank storage is a little too far for convenience.

**Comment by Tokeli** [comment]
Janitor needs keys for the pimpin' ride.

**Comment by TheMocheeze** [comment]
Change cabin door name numbers to be accurate

**Comment by ShrkByte** [comment]
> @Tokeli  Janitor needs keys for the pimpin' ride.

image

I see a key on top of the pimpin' ride

**Comment by TheMocheeze** [comment]
AI sat & upload turret controls

**Comment by ShrkByte** [comment]
Cryo's door should be a windoor instead of a secure door like the rest of the dorms.

**Pull request merged**
